### ISSUE TITLE
Unable to generate classes from interfaces - what am I doing wrong?

### ISSUE THREAD

**Issue by fluffynuts** [Box-Of-Hats/vscode-ts-to-cs#11]
Hi

I have an interface in ts:

```typescript
import { DateTime } from "luxon";
import { MappingProviders } from "@/models/mapping/mapping-providers";

export interface IAddress {
    Id: number;
    Name: string;
    AddressLine1: string;
    AddressLine2: string;
    Number: string;
    Street: string;
    Province: string;
    Latitude: number;
    Longitude: number;
    DisplayText: string;
    FullAddress: string;
    NameAndStreet: string;
    OriginalAddressId?: number;
    DistanceToCurrentLocation?: number;
    IsValidAddress: boolean;
    IsCurrentLocation: boolean;
    IsPointOfInterest: boolean;
    MappingProvider: MappingProviders;
    DateSelected?: DateTime;
}
```

and `mapping-providers` has this:
```typescript
export enum MappingProviders {
    Google = "Google",
    MapBox = "MapBox"
}
```

I've tried highlighting the interface, placing the cursor on the interface's name, on `interface`, anywhere in the file, selecting all the text in the file - no matter what I do, when I subsequently ctrl-shift-p and select `TS => CS: Generate classes from interfaces`, I get:

![image](https://user-images.githubusercontent.com/4669340/152327674-f5c6514b-e3ed-414a-b492-e141b02fff5f.png)

I only have the following extensions installed:

![image](https://user-images.githubusercontent.com/4669340/152327914-a2ed0895-03db-4b52-ab31-54094aa9571a.png)

(side-note: it would also be neat to be able to generate interfaces rather than classes, but this is a minor change I was willing to deal with - it's just one word change)

**Comment by Box-Of-Hats** [comment]
Thanks for raising this and providing the extra details. This was a bug where it would fail to generate a class if a property name included numbers.

This has now been fixed in version v0.2.3
