### ISSUE TITLE
[ERROR] Can't Install VSIX!

### ISSUE THREAD

**Issue by Soi9x** [Box-Of-Hats/vscode-ts-to-cs#12]
![image](https://user-images.githubusercontent.com/94919121/156870775-06db178f-d4bb-46ea-978b-5a6acb48ba41.png)
Hi I can't install it on visual Studio 2019 & 2022 , Please give a solution to fix it , thanks

**Comment by Box-Of-Hats** [comment]
Hi, this extension is for [Visual Studio Code](https://code.visualstudio.com) and not Visual Studio.
You won't be able to install it on VS 2022 or 2019 as they are different applications
