### ISSUE TITLE
Unable to install the extension in Visual Studio 2019

### ISSUE THREAD

**Issue by sureshp191** [Box-Of-Hats/vscode-ts-to-cs#4]
After downloading the extension, I tried to install but I got the error its for Visual Studio Code. Like to know whether its for both or only for Visual Studio Code? Please advise thanks.
![Screenshot 2021-01-16 115257](https://user-images.githubusercontent.com/26474888/104819244-d9ef3700-57f1-11eb-9dd4-4ee607212fb3.png)

**Comment by Box-Of-Hats** [comment]
The extension is only for VSCode so it won't work on Visual Studio unfortunately
