### ISSUE TITLE
Converter doesn't work at all

### ISSUE THREAD

**Issue by nikita-rostovskiy** [Box-Of-Hats/vscode-ts-to-cs#6]
Could you please update wiki with clarification about how to run convertion, what files should be opened, how extention should be configured. I opened my typescript file with "export default interface IUserInterface..." and tried to run that 2 commands you described on wiki but the only result I got is error message that said it couldn't find any interface. What do I do wrong?

**Comment by siva538** [comment]
Hello @Box-Of-Hats , am getting exactly same behavior after I installed this plugin. Can you please let me know if there is a way to generate the export interfaces, classes, and even the functions ? Thanks a lot.

Here is the error message I was getting - "Could not find any interfaces to generate from". 

![image](https://user-images.githubusercontent.com/36265138/120897209-954e2600-c642-11eb-9f68-e26a1cc49cfc.png)

**Comment by Box-Of-Hats** [comment]
Hi @siva538, @nikita-rostovskiy.

Thanks for bringing this to my attention. Previously, you needed to highlight whatever interfaces you wanted to export. I've just released an update (0.2.1) which defaults to the whole document if you haven't got a selection.

Please try again after updating and let me know if you're still having troubles
